### ISSUE TITLE
[AVM Module Issue]: Default example blocks compute from accessing public resources

### ISSUE THREAD

**Issue by inchiosa** [Azure/terraform-azurerm-avm-res-machinelearningservices-workspace#27]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

To repro the bug, deploy the "default" example. Observe that "Workspace managed outbound access" is set to "Allow Internet Outbound" rather than "Disabled".

Default example:

<img width="774" alt="image" src="https://github.com/user-attachments/assets/5255ba51-b148-4420-9f15-111fb7cda25b">

AML Workspace created from the Portal using default settings:

<img width="771" alt="image" src="https://github.com/user-attachments/assets/1a5ad8b1-5f41-4707-a3a1-8cf478d3415f">

**Comment by ritesh-modi** [comment]
module "azureml" {
  source = "../../"
  # source             = "Azure/avm-<res/ptn>-<name>/azurerm"
  # ...
  location = var.location
  name     = module.naming.machine_learning_workspace.name_unique
  resource_group = {
    name = azurerm_resource_group.this.name
    id   = azurerm_resource_group.this.id
  }
   is_private = false
  enable_telemetry = var.enable_telemetry
}

 adding  is_private = false should fix this

**Comment by soallam** [comment]
@oloomi  please take a look at the comment above

**Comment by cmaclaughlin** [comment]
If "default" is intended to align with Azure Portal default, then shouldn't the "default" example have `is_private` variable to true? 

Also, the description for the `is_private` variable is extremely ambiguous.

**Comment by cmaclaughlin** [comment]
Completed with PR #39
