### ISSUE TITLE
[AVM Question/Feedback]:

### ISSUE THREAD

**Issue by shivam-51** [Azure/terraform-azurerm-avm-res-machinelearningservices-workspace#97]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

How to add FQDN rules while creating a new AML workspace?
I see there is a `outbound_rules` input parameter but that only accepts resource id which means there's no way to add FQDN.

**Comment by cmaclaughlin** [comment]
At this point, there is no way to do so with this module. This functionality should be included in / covered with the completion of #64 .
